systemProp.imVersion=5.1.0.4
systemProp.bioVersion=5.1.0.4
systemProp.blueGenesVersion=1.0.+

systemProp.javax.xml.stream.XMLOutputFactory=com.sun.xml.internal.stream.XMLOutputFactoryImpl
#not sure if this setting still needed, now that I'm back to using java 11
#org.gradle.jvmargs=--add-opens=java.base/java.lang=ALL-UNNAMED
org.gradle.jvmargs=-Xmx400g -XX:+HeapDumpOnOutOfMemoryError
